services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    entrypoint: 
      - "redis-server"
      - "--requirepass"
      - $REDIS_PASSWORD
  